config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'events#index'

  resources :events
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord


	belongs_to :user
	belongs_to :event
	
	def inscription_event_send
		UserMailer.inscription_event(self).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord

	validates :start_date, presence: true 
	validates :duration, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
	
	#le validate des méthodes est au singulier
	validate :multiple_of_5
	
	validates :title, presence: true, length: {minimum: 5, maximum: 140}
	validates :description, presence: true, length: {minimum: 20, maximum: 1000}
	validates :price, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 1000}
	validates :location, presence: true

	has_many :attendances
	has_many :users, through: :attendances
	belongs_to :admin, class_name: "User"

	def multiple_of_5
      if (self.duration % 5) != 0
      self.errors[:base] << "Number must be divisible by 5!"
      end
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send

  has_many :attendances 
  has_many :events, through: :attendances

  #to make a difference between the users who organise events and the users who participate only
	has_many :organisers, foreign_key: 'admin_id', class_name: "Event"


  def welcome_send
  	UserMailer.welcome_email(self).deliver_now	
  end

end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
  end

  def new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class = "jumbotron">

  <h1>Bienvenue sur EventBriitee</h1>
		<h4>Tu trouveras les meilleures soirées de ta ville ou d'ailleurs...</h4>
		</br>
			<h6>Pour proposer un evenement, c'est <a> <%= link_to "ici !", new_event_path %> </a> </h6>
</div>


 <% if flash[:success] %>
      <div class="alert alert-success" role="alert"><%= flash[:success] %></div>
 <% elsif flash[:danger] %>
      <div class="alert alert-danger" role="alert"><%= flash[:danger] %></div>
   <% end %>

    <h5 class="h1-responsive font-weight-bold my-5">Voici les événements à venir...</h5>


<section>
<div class="card-deck">
<%Event.all.each do |event|%>
<div class="col-sm-5 mb-3">
<div class="card">
  <div class="card-header">
    <%=event.start_date%>
  </div>
  <div class="card-body align-center">
    <blockquote class="blockquote mb-0">
      <p><%=event.title%></p>
      <footer class="blockquote-footer">
      <div class="row justify-content-between align-self-center mx-3">
        <p><%=event.price%> €</p>
        <a class="btn btn-bg bg-primary" <%= link_to "show me!", event_path(event.id)%></a>
      </div>
      </footer>
    </blockquote>
  </div>
</div>
</div>
<%end%>
</div>
</section>

app/views/events/new.html.erb
<h2 class="h1-responsive font-weight-bold my-5">Page de création d'un nouvel événement</h2>

<body>

	  
	  <p class="h4 mb-4"> Pour créer un nouvel événement, remplissez le formulaire ci-dessous </p>

app/views/events/show.html.erb
<h2 class="h1-responsive font-weight-bold my-5">Bienvenue sur la page de l'event n°<%= @event.id %></h2>

		<div class="my-3 p-3 bg-white rounded box-shadow text-success">
   

        <div class="media text-dark pt-3"> 
          <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">TITRE</strong>
            <%= @event.title%>
          </p>
        </div>

        <div class="media text-dark pt-3">  
          <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">DESCRIPTION</strong>
            <%= @event.description%>
          </p>
        </div>

        <div class="media text-dark pt-3"> 
          <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">DATE</strong>
          		<a> <%= @event.start_date %> </a>
          </p>
        </div>

         <div class="media text-dark pt-3"> 
          <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">DUREE</strong>
            <a> <%= @event.duration %> minutes </a>
          </p>
        </div>

         <div class="media text-dark pt-3"> 
          <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">PRICE</strong>
            <a> <%= @event.price %>€ </a>
          </p>
        </div>

         <div class="media text-dark pt-3"> 
          <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">LOCATION</strong>
            <a> <%= @event.location %> </a>
          </p>
        </div>

        <div class="media text-dark pt-3"> 
          <p class="media-body pb-3 mb-0 medium lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">ORGANISATEUR</strong>
            <a> XXX </a>
          </p>
        </div>

      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Bootswatch SUPERHERO-->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/superhero/bootstrap.min.css" rel="stylesheet" integrity="sha384-LS4/wo5Z/8SLpOLHs0IbuPAGOWTx30XSoZJ8o7WKH0UJhRpjXXTpODOjfVnNjeHu" crossorigin="anonymous">

    <title>Eventbriitee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <!-- Navigation bar-->

  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">EventBriitee</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="true" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
       <div class="navbar-collapse collapse show" id="navbarColor03" style="">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" <%= link_to "Accueil", root_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" <%= link_to "Créer un événement", new_event_path %></a>
            </li> 
          </ul>


      <%if user_signed_in?%> 
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" navbar-text= "#fff" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Mon profil
          </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" navbar-text "white" <%= link_to "Mon profil", root_path %></a>  
              <a class="dropdown-item" <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></a>
            </div>
        </div> 


        <%else%>
                
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" .navbar-text= "#fff" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            S'inscrire / Se connecter
          </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" <%= link_to "S'inscrire", new_user_registration_path %></a>
              <a class="dropdown-item" <%= link_to "Se connecter", new_user_session_path %></a>
            </div>
        </div>

        <%end%>
    </nav>

    <%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>